"""add officer decision columns

Revision ID: 5ab57204f214
Revises: 74d8a747506b
Create Date: 2026-09-17 03:12:17.364834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab57204f214'
down_revision: Union[str, Sequence[str], None] = '74d8a747506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('officer_action', sa.String(length=32), nullable=True))
    op.add_column('screenings', sa.Column('officer_notes', sa.Text(), nullable=True))
    op.add_column('screenings', sa.Column('decided_at', sa.DateTime(), nullable=True))
    op.add_column('screenings', sa.Column('decided_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'decided_by')
    op.drop_column('screenings', 'decided_at')
    op.drop_column('screenings', 'officer_notes')
    op.drop_column('screenings', 'officer_action')
    # ### end Alembic commands ###
