"""initial schema

Revision ID: 74d8a747506b
Revises: 
Create Date: 2026-09-17 02:49:36.005484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d8a747506b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_priority', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_id'), 'screenings', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('document_number_hash', sa.String(length=128), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('object_reference', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_id'), 'evidence_items', ['id'], unique=False)
    op.create_table('external_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_reference', sa.String(length=256), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_checks_id'), 'external_checks', ['id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_id'), 'extracted_fields', ['id'], unique=False)
    op.create_table('face_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_results_id'), 'face_results', ['id'], unique=False)
    op.create_table('tampering_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tampering_results_id'), 'tampering_results', ['id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('screening_id', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_tampering_results_id'), table_name='tampering_results')
    op.drop_table('tampering_results')
    op.drop_index(op.f('ix_face_results_id'), table_name='face_results')
    op.drop_table('face_results')
    op.drop_index(op.f('ix_extracted_fields_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_external_checks_id'), table_name='external_checks')
    op.drop_table('external_checks')
    op.drop_index(op.f('ix_evidence_items_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_screenings_id'), table_name='screenings')
    op.drop_table('screenings')
    # ### end Alembic commands ###
